# Site settings
title: Samuel Lozano Iglesias
email: samuloza@ucm.es
baseurl: ""  # Déjalo vacío para GitHub Pages.
url: "https://samuellozanoiglesias.github.io"  # Sustituye con la URL real de tu blog.
keywords: "science, investigation, mathematics, physics, machine learning, reinforcement learning, cooperative behaviour"
skills: "ML Researcher - Mathematician - Physicist"
meta_author: Samuel Lozano Iglesias

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 004D40  # Verde oscuro (moderno y profesional).
  primary-rgb: "0,77,64"
  secondary: 006064  # Azul oscuro.
  secondary-dark: 004346
  
# Footer settings
footer:
  copyright: © 2024 Samuel Lozano Iglesias
  location: Madrid, España
  social: Feel free to contact me!
  credits: "Univerisdad Complutense de Madrid"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/samuel-lozano-iglesias-202336200/
  - title: github
    url: http://github.com/samuellozanoiglesias

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
